server:
  address: localhost
  port: 8080
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
authorize:
  email:
    template-path: authorize/mail
    title: "[미닛메이트] 인증메일이 도착했어요"